# Test cases for the Atlantis module
name: Atlantis Module Tests

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '.github/workflows/test.yml'

jobs:
  terraform-validate:
    name: Validate Terraform Configuration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: |
          cd tests/minimal
          terraform init
          cd ../private-alb
          terraform init

      - name: Terraform Validate Minimal Config
        run: |
          cd tests/minimal
          terraform validate

      - name: Terraform Validate Private ALB Config
        run: |
          cd tests/private-alb
          terraform validate

  terraform-format:
    name: Check Terraform Formatting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Check formatting
        run: terraform fmt -check -recursive

  tflint:
    name: Run TFLint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1

      - name: Run TFLint
        run: |
          tflint --init
          tflint -f compact
